---

- hosts: all
  gather_facts: true

  # Register the Ansible Variables
  vars:
    debug: false
    sendRequest: true
    lastUpdate: "{{ansible_date_time.date}}:{{ansible_date_time.time}}"
    epoch: "{{ansible_date_time.epoch}}"
    register_master: false;
    register_node: false;

  # defines the Ansible tasks

  tasks:

  # Print the hostname
  - name: Print The hostname when ansible-master
    ansible.builtin.debug:
      var: inventory_hostname
    when: inventory_hostname == "ansible-master"

  # Cut the Uptime from the results
  - name: Check uptime
    shell: cut -d ' ' -f1 /proc/uptime
    register: uptimeoutput

  - name: Test 
    ansible.builtin.debug:
      var: uptimeoutput.stdout_lines[0]
    when: uptimeoutput.stdout_lines[0] == "VARIABLE IS NOT DEFINED!" and  inventory_hostname == "ansible-master"

  # Print the uptime
  - name: Print The uptime
    ansible.builtin.debug:
      var: uptimeoutput.stdout_lines[0]
    when: debug

  # Print the current date
  - name: Print the current date
    ansible.builtin.debug:
      #var: ansible_date_time.date
      var: lastUpdate
    when: debug

  # Initialize the hostname
  - name: Initialize the hostname data object
    ansible.builtin.set_fact:
      serverstatus: {"hostname":"{{ inventory_hostname }}","uptime":"{{uptimeoutput.stdout_lines[0] }}","lastupdate":"{{lastUpdate}}","epoch":"{{epoch}}" }

  # Print the serverstatus
  - name: Print the serverstatus
    ansible.builtin.debug:
      var: serverstatus
    when: debug

  # nodeport - "http://nginx.ingress.192.168.1.100.nip.io:30850/uptime"
  # ingress - "http://nginx.ingress.192.168.1.100.nip.io:8085/uptime"


  - name: POST from contents of local file
    ansible.builtin.uri:
      url: "http://nginx.ingress.192.168.1.100.nip.io:30850/uptime"
      method: POST
      return_content: yes
      body_format: "json"
      body: "{{ serverstatus }}"
      status_code: 201
    when: sendRequest

  - name: Set register_master
    ansible.builtin.set_fact:
      register_master: true
    ignore_unreachable: true
    when: (inventory_hostname == "ansible-master") and (uptimeoutput.stdout is undefined )

  # Print the register_master
  - name: Print The register_master
    ansible.builtin.debug:
      var: register_master
    ignore_unreachable: true
    #when: debug

  - name: Set register_node
    ansible.builtin.set_fact:
      register_node: true
    ignore_unreachable: true
    when: inventory_hostname | select('ubuntu-node') | list | count > 0
    #when: (inventory_hostname == "ansible-master") and (uptimeoutput.stdout is undefined )

  # Print the register_node
  - name: Print The register_node
    ansible.builtin.debug:
      var: register_node
    ignore_unreachable: true
    #when: debug

      
