# https://docs.docker.com/build/building/best-practices/
# docker build --no-cache -t ubuntu-ansible .
# docker build --no-cache --add-host ansible-master:172.17.0.10 -t ubuntu-ansible .
# docker build --no-cache --add-host ansible-master:172.17.0.10 -t ubuntu-ansible . -f Dockerfile-ansible-master   <--- use this one

# docker run -dt -h ansible --name ubuntu-ansible ubuntu-ansible

# docker exec -it ubuntu-ansible  //bin//bash   windows

# docker stop ubuntu-ansible
# docker rm ubuntu-ansible
# docker image rm ubuntu-ansible
# docker stop ubuntu-ansible; docker rm ubuntu-ansible; docker image rm ubuntu-ansible


# docker debug <id>
# crontab -l
# crontab -e
# 30 * * * * /ops/ansible/hoststatus.sh
#  5 * * * * /ops/ansible/uptime.sh
# * * * * * echo "Hello world" >> /var/log/cron.log 2>&1

FROM ubuntu:latest
RUN apt-get -y update && apt-get install -y python3; \
apt-get install -y ansible; \
apt-get install -y openssh-server; \
apt-get install -y sshpass; \
apt-get install -y vim; \
apt-get install -y cron; \
apt-get install -y curl; \
apt-get install -y gcc; \
apt-get install -y iputils-ping; \
apt-get install -y python3-pip

RUN mkdir -p /ops
RUN mkdir -p /setup
RUN chmod 777 /setup
COPY ./hosts /setup/hosts
COPY ./password.txt /setup/password.txt
COPY ./setup-master.sh /setup/setup-master-hostfile.sh
RUN chmod 777 /setup/setup-master-hostfile.sh
COPY ./add-host-hostfile.sh /setup/add-host-hostfile.sh
RUN chmod 777 /setup/add-host-hostfile.sh
# COPY ./setup-ansadmin.sh /setup/setup-ansadmin.sh
# RUN chmod 777 /setup/setup-ansadmin.sh
# COPY ./restart-ssh-service.sh /setup/restart-ssh-service.sh
# RUN chmod 777 /setup/restart-ssh-service.sh
# COPY ./setup-cloud-nodes.sh /setup/setup-cloud-nodes.sh
# RUN chmod 777 /setup/setup-cloud-nodes.sh
# COPY ./run-status.sh /setup/run-status.sh
# RUN chmod 777 /setup/run-status.sh
COPY ./docker-master-entrypoint.sh /setup/docker-master-entrypoint.sh
RUN chmod +x /setup/docker-master-entrypoint.sh
COPY ./setup-ssh-keys.sh /setup/setup-ssh-keys.sh
RUN chmod +x /setup/setup-ssh-keys.sh

WORKDIR /ops
COPY ./ansible /ops/ansible
RUN chmod 777 /ops/ansible
RUN chmod 777 /ops/ansible/*.*

RUN groupadd -g 1001 ansadmin && \
    useradd -m -u 1001 -g ansadmin ansadmin -p ansadmin
RUN echo "ansadmin:ansadmin" | chpasswd

#COPY ./cron/crontab /etc/crontab
COPY ./cron/crontab /etc/cron.d/crontab
#COPY /etc/hosts /etc/hosts.org
COPY ./hosts /etc/hosts
COPY ./cron/crontab /var/spool/cron/crontabs/ansadmin
COPY ./ssh_config /etc/ssh/ssh_config
COPY ./ansible.cfg /home/ansadmin/ansible.cfg
RUN chown ansadmin:ansadmin /home/ansadmin/ansible.cfg
#RUN chmod 0644 /etc/cron.d/crontab
RUN chown ansadmin:crontab /var/spool/cron/crontabs/ansadmin
RUN chmod 600 /var/spool/cron/crontabs/ansadmin
RUN chmod 777 /var/log
RUN touch /var/log/cron.log
RUN chmod 777 /var/log/cron.log
RUN touch /var/log/ops.log
RUN chmod 777 /var/log/ops.log

#RUN /setup/docker-master-entrypoint.sh

#RUN service ssh restart  # did not work
#RUN systemctl restart ssh

#USER ansadmin

#ENTRYPOINT ["/setup/setup-ansadmin.sh"]

ENTRYPOINT ["/setup/docker-master-entrypoint.sh"]

USER root
CMD ["cron", "-f", "tail -f /var/log/cron.log"]